<a href="https://colab.research.google.com/github/Tongjai-Yampaka/Deep-US/blob/master/pycuda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pycuda

     |████████████████████████████████| 1.6MB 2.8MB/s 
     |████████████████████████████████| 61kB 7.7MB/s 
     |████████████████████████████████| 471kB 47.5MB/s 
  Created wheel for pycuda: filename=pycuda-2019.1.2-cp36-cp36m-linux_x86_64.whl size=4536165 sha256=089131389ff778e711a773f02195c621096ac11c63ac474d0cdc3bc1ca94765d
  Stored in directory: /root/.cache/pip/wheels/a6/60/f0/b1c430c73d281ac3e46070480db50f7907364eb6f6d3188396
  Created wheel for pytools: filename=pytools-2019.1.1-py2.py3-none-any.whl size=58424 sha256=9e255da0c8289e7773960c4337e45cc02adbca315fbdece877c35773cd234352
  Stored in directory: /root/.cache/pip/wheels/83/df/0b/75ac4572aaa93e3eba6a58472635d0fda907f5f4cf884a3a0c
  Created wheel for mako: filename=Mako-1.1.0-cp36-none-any.whl size=75363 sha256=779590270f4935264fb0c74af83766288e454daa1bfaea4632d8346f75920256
  Stored in directory: /root/.cache/pip/wheels/98/32/7b/a291926643fc1d1e02593e0d9e247c5a866a366b8343b7aa27
Successfully built pycuda pytools mako


In [18]:
from pycuda import autoinit
from pycuda import gpuarray
import numpy as np

# Initialize vectors "a" and "b" with some numbers,
# and vector "c" with zeros
# Use numpy to define single precision vectors
N = range(10)
a = np.array(N).astype(np.float32)
b = (a*a).astype(np.float32)
c = np.zeros(len(N)).astype(np.float32)

# Create the corresponding vectors in GPU memory
a_gpu = gpuarray.to_gpu(a)
b_gpu = gpuarray.to_gpu(b)
c_gpu = gpuarray.to_gpu(c)

# Perform the vector addition on the GPU
c_gpu = a_gpu+b_gpu

# Collect the result from GPU memory
c = c_gpu.get()

print(a)
print(b)
print(c)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
[ 0.  2.  6. 12. 20. 30. 42. 56. 72. 90.]
